# Generated by Django 5.1.7 on 2025-03-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubEmail',
        ),
    ]
