# Generated by Django 5.1.7 on 2025-03-15 01:27

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('views', models.BigIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies')),
                ('premiere_date', models.DateField(blank=True, null=True)),
                ('from_the_movie', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('trailer', models.FileField(blank=True, null=True, upload_to='trailers')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_movie', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_movie', to='category.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='tag_movie', to='category.tag')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
